#ifndef head_files_h
#define head_files_h

#include "_def.h"
#include "algoritm.h"
//#include "blink.h"
//#include "adc.h"
//#include "alg.h"
//#include "backlight.h"
//#include "bmp180.h"
//#include "calclux.h"
#include "convert2ascii.h"
//#include "din_ind.h"
//#include "ds1307.h"

#include "eep_328.h"
//#include "errors_i2c.h"
//#include "heater.h"
//#include "i2c.h"
#include "ISR_timers.h"
#include "KN1.h"
#include "KN2.h"
//#include "KN3.h"
//#include "KN4.h"
//#include "KN5.h"
#include "led.h"
#include "lcd1602.h"
#include "maintimer32.h"
//#include "menu.h"
#include "messages.h"
//#include "quick.h"
#include "releaseguard.h"
#include "setup.h"
#include "set_income.h"
//#include "sim800l.h"
#include "uart328_sh.h"
#include "wdt.h"


#endif
